# Generated by Django 3.2 on 2021-06-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=3)),
                ('NumOfPupils', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNumber', models.CharField(max_length=4)),
                ('Capacity', models.IntegerField(default=0)),
                ('RoomChoice', models.CharField(max_length=12)),
                ('Block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Count', models.IntegerField(default=0)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonsWeekly', models.IntegerField(default=0)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('SubjectTeach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('Class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thr', 'Thursday'), ('Fri', 'Friday')], max_length=3)),
                ('Unit', models.CharField(choices=[('Unit1', 'Unit 1'), ('Unit2', 'Unit 2'), ('Form', 'Form'), ('Unit3', 'Unit 3'), ('Unit4', 'Unit 4'), ('Unit5', 'Unit 5')], max_length=6)),
                ('ClassGroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.classgroup')),
                ('Room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('Subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('Teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='Timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timeslot'),
        ),
        migrations.AddField(
            model_name='subject',
            name='yearGroup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.yeargroup'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='Subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
    ]
