# Generated by Django 3.2 on 2021-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='RoomChoice',
            field=models.CharField(choices=[('ClassRoom', 'Class Room'), ('ComputerRoom', 'Computer Room')], max_length=12),
        ),
    ]
