# Generated by Django 3.2 on 2021-06-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_roomchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='RoomChoice',
            new_name='RoomType',
        ),
    ]
