# Generated by Django 3.2 on 2021-06-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_roomchoice_room_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeargroup',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classgroup'),
        ),
    ]
