# Generated by Django 3.2 on 2021-06-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_yeargroup_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='Subjects',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='Subjects',
            field=models.ManyToManyField(blank=True, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Block',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.block'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='block',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.block'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='yearGroup',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.yeargroup'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Room',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Room',
            field=models.ManyToManyField(blank=True, to='api.Room'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='SubjectTeach',
        ),
        migrations.AddField(
            model_name='teacher',
            name='SubjectTeach',
            field=models.ManyToManyField(blank=True, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Timeslot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.timeslot'),
        ),
        migrations.RemoveField(
            model_name='yeargroup',
            name='Class',
        ),
        migrations.AddField(
            model_name='yeargroup',
            name='Class',
            field=models.ManyToManyField(blank=True, to='api.ClassGroup'),
        ),
    ]
