# Generated by Django 3.2 on 2021-06-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210610_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='block',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.block'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='yearGroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.yeargroup'),
        ),
    ]
