# Generated by Django 3.2 on 2021-06-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timeslot'),
        ),
    ]
