# Generated by Django 3.2 on 2021-06-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_teacher_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Timeslot',
        ),
    ]
