# Generated by Django 3.2 on 2021-06-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_teacher_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeargroup',
            old_name='Class',
            new_name='classes',
        ),
        migrations.AlterField(
            model_name='room',
            name='Block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.block'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.block'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='yearGroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeargroups', to='api.yeargroup'),
        ),
    ]
