# Generated by Django 3.2 on 2021-06-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210613_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeargroup',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
