# Generated by Django 3.2 on 2021-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_yeargroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
