# Generated by Django 3.2 on 2021-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Description',
            field=models.CharField(choices=[('Science', 'Science'), ('Computing', 'Computing'), ('Food', 'Food'), ('Art', 'Art'), ('Construction', 'Construction'), ('English', 'English'), ('Hums', 'Hums'), ('ICT', 'ICT'), ('P16', 'P16'), ('Maths', 'Maths'), ('PE', 'PE'), ('BSt', 'BSt'), ('MFL', 'MFL'), ('Music', 'Music'), ('Sp Hall', 'Sp Hall'), ('Nurture', 'Nurture'), ('Dr St', 'Dr St'), ('Da St', 'Da St')], max_length=50, null=True),
        ),
    ]
