# Generated by Django 3.2 on 2021-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='classCode',
            field=models.CharField(max_length=10),
        ),
    ]
