# Generated by Django 3.2 on 2021-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_classgroup_classcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='Day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3),
        ),
    ]
