# Generated by Django 3.2 on 2022-05-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_timeslot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subjects', models.ManyToManyField(blank=True, to='api.Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SubjectTeach',
            field=models.ManyToManyField(blank=True, to='api.SubjectGroup'),
        ),
    ]
